Repository xornet-cloud/Xornet, pull requests merged in 2021-06, with the labels that each got.

#76 Optimized cpu usage calculation for windows
  .gitignore
  client/src/App.vue
  client/src/components/dashboard/DatacenterButton.vue
  client/src/components/dashboard/Header.vue
  client/src/components/dashboard/Logo.vue
  client/src/components/dashboard/MultiGauge.vue
  client/src/components/dashboard/Nav.vue
  client/src/components/dashboard/SearchBar.vue
  client/src/components/dashboard/ServerList.vue
  client/src/components/dashboard/ServerListButton.vue
  client/src/components/home/Header.vue
  client/src/components/misc/LoginCard.vue
  client/src/components/misc/SpecProperty.vue
  client/src/main.js
  client/src/router/index.js
  client/src/views/dashboard/Dashboard.vue
  client/src/views/dashboard/Datacenters.vue
  client/src/views/dashboard/Machines.vue
  client/src/views/dashboard/Settings.vue
  client/src/views/dashboard/Specs.vue
  client/src/views/home/Downloads.vue
  client/src/views/home/Login.vue
  reporter/package-lock.json
  reporter/package.json
  reporter/util/clearLastLine.js
  reporter/util/getCpuUsage.js
  reporter/util/getStaticData.js
  reporter/util/getStats.js
  reporter/util/speedtest.js
Labels: enhancement, reporter

#81 Add tooltip to profile badges
  client/src/components/dashboard/Tooltip.vue
  client/src/views/dashboard/Profile.vue
Labels: enhancement, frontend, good first issue

#84 added badge changing for users
  client/src/App.vue
  client/src/views/dashboard/Profile.vue
Labels: enhancement, frontend, good first issue

#86 refactored the entire front end CSS
  client/src/components/dashboard/ColoredGauge.vue
  client/src/components/dashboard/DatacenterButton.vue
  client/src/components/dashboard/Gauge.vue
  client/src/components/dashboard/GaugeField.vue
  client/src/components/dashboard/Header.vue
  client/src/components/dashboard/InfoField.vue
  client/src/components/dashboard/LoadingScreen.vue
  client/src/components/dashboard/LogButton.vue
  client/src/components/dashboard/MachineButton.vue
  client/src/components/dashboard/MemberField.vue
  client/src/components/dashboard/MobileNav.vue
  client/src/components/dashboard/MultiGauge.vue
  client/src/components/dashboard/SearchBar.vue
  client/src/components/dashboard/SearchResult.vue
  client/src/components/dashboard/ServerList.vue
  client/src/components/dashboard/ServerListButton.vue
  client/src/components/home/Header.vue
  client/src/components/home/Main.vue
  client/src/components/misc/Popup.vue
  client/src/components/misc/card.css
  client/src/views/dashboard/Dashboard.vue
  client/src/views/dashboard/Datacenters.vue
  client/src/views/dashboard/Profile.vue
  client/src/views/dashboard/Specs.vue
  client/src/views/home/Login.vue
  client/src/views/home/Signup.vue
Labels: enhancement, frontend

#91 pfp previews + a little bit of windi
  client/src/views/dashboard/Profile.vue
Labels: enhancement, frontend, good first issue

#142 French Translation
  reporter/lang/fr-FR.json
Labels: reporter, translations

#161 Create Windows install scripts for #160 (see note)
  reporter/install-windows/install.bat
  reporter/install-windows/install.ps1
Labels: enhancement, reporter

#172 add TS + fixed palette + dialog component but it breaks the add server thing
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/components/HelloWorld.vue
  client/src/components/library/Card.vue
  client/src/components/library/Dialog.vue
  client/src/main.ts
  client/src/services/api/Base.js
  client/src/shims-vue.d.ts
  client/src/views/Home.vue
  client/src/views/dashboard/Datacenters.vue
  client/tsconfig.json
  client/vue.config.js
  client/windi.config.ts
Labels: enhancement, frontend

#177 Update fil_PH.json
  reporter/lang/fil_PH.json
Labels: reporter, translations

#178 Added translations for ben-BD
  reporter/lang/ben-BD.json
Labels: reporter, translations

#181 Fix config??
  README.md
  client/vue.config.js
Labels: frontend

#184 added QR Code creation to machines
  client/package.json
  client/src/assets/icons/filled/print.svg
  client/src/assets/icons/filled/qr.svg
  client/src/assets/icons/stroked/print.svg
  client/src/assets/icons/stroked/qr.svg
  client/src/components/dashboard/QRDialog.vue
  client/src/components/library/Card.vue
  client/src/views/dashboard/Machine.vue
Labels: enhancement, frontend

#185 updated QR component and added Switch component
  client/src/components/dashboard/QRDialog.vue
  client/src/components/library/Switch.vue
  client/src/views/dashboard/Datacenters.vue
  client/src/views/dashboard/Machine.vue
  client/src/views/dashboard/Settings.vue
Labels: enhancement, frontend
