Repository xornet-cloud/Xornet, pull requests merged in 2021-07, with the labels that each got.

#188 Give tooltip proper direction and color options
  client/package-lock.json
  client/package.json
  client/src/components/dashboard/Nav.vue
  client/src/components/dashboard/Tooltip.vue
  client/src/views/dashboard/Machines.vue
Labels: enhancement, frontend

#199 fixed PWA manifest & better auth & setting icons
  .gitignore
  client/public/manifest.json
  client/src/assets/icons/filled/counter.svg
  client/src/assets/icons/filled/fill.svg
  client/src/assets/icons/stroked/counter.svg
  client/src/assets/icons/stroked/fill.svg
  client/src/components/dashboard/SettingsButton.vue
  client/src/components/dashboard/settings/Appearance.vue
  client/src/components/dashboard/settings/Setting.vue
  client/src/components/library/Switch.vue
  client/src/services/api/Base.js
  server/index.js
  server/middleware/auth.js
  server/routes/login.js
Labels: backend, enhancement, frontend

#204 improve development experience and added custom UUIDs
  .gitignore
  client/.prettierrc
  client/package-lock.json
  client/package.json
  client/src/assets/icons/filled/counter.svg
  client/src/assets/icons/filled/fill.svg
  client/src/assets/icons/stroked/counter.svg
  client/src/assets/icons/stroked/fill.svg
  client/src/components/dashboard/CoreBars.vue
  client/src/components/dashboard/settings/Appearance.vue
  client/src/components/dashboard/settings/Setting.vue
  client/src/services/api/Base.js
  client/src/services/socket.js
  client/src/views/dashboard/Settings.vue
  client/src/views/home/Downloads.vue
  client/vue.config.js
  reporter/.prettierrc
  reporter/index.js
  reporter/install-linux/install.sh
  reporter/install-linux/xornet.service
  reporter/install-windows/install.ps1
  reporter/nodemon.json
  reporter/package-lock.json
  reporter/package.json
  reporter/util/checkAccount.js
  reporter/util/connectToXornet.js
  reporter/util/downloadLanguage.js
  reporter/util/getStaticData.js
  reporter/util/getStats.js
  reporter/util/logger.js
  reporter/util/restart.js
  reporter/util/settings.js
  reporter/util/shutdown.js
  reporter/util/speedtest.js
  server/.prettierrc
  server/index.js
  server/middleware/auth.js
  server/package-lock.json
  server/package.json
  server/routes/profile.js
  server/services/sockets.js
  server/util/parseReport.js
  server/util/saveImage.js
Labels: backend, bug, enhancement, reporter

#205 fixed small mistakes and #202
  client/package.json
  client/src/App.vue
  client/src/components/dashboard/SearchBar.vue
  client/src/components/dashboard/ServerListButton.vue
  client/src/components/dashboard/settings/Appearance.vue
  client/src/views/dashboard/Machine.vue
  client/vue.config.js
Labels: bug, frontend

#206 hid unused setting components for now
  client/src/components/dashboard/settings/Interface.vue
  client/src/views/dashboard/Settings.vue
Labels: frontend

#207 added Tag component and Icons
  client/.prettierrc
  client/src/components/library/Tag.vue
  client/src/views/dashboard/Machines.vue
Labels: enhancement, frontend

#220 added reporter sending the settings to the backend and tab toggling
  client/src/components/dashboard/Tabs.vue
  client/src/components/dashboard/Terminal.vue
  client/src/views/dashboard/Datacenters.vue
  client/src/views/dashboard/Machine.vue
  reporter/index.js
  reporter/package-lock.json
  reporter/util/getStaticData.js
  reporter/util/getStats.js
  reporter/util/settings.js
Labels: enhancement, frontend, reporter
